# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fran/Documents/CXX/chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fran/Documents/CXX/chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fran/Documents/CXX/chat/CMakeFiles /home/fran/Documents/CXX/chat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fran/Documents/CXX/chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clientui

# Build rule for target.
clientui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientui
.PHONY : clientui

# fast build rule for target.
clientui/fast:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/build
.PHONY : clientui/fast

#=============================================================================
# Target rules for targets named serverui

# Build rule for target.
serverui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serverui
.PHONY : serverui

# fast build rule for target.
serverui/fast:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/build
.PHONY : serverui/fast

#=============================================================================
# Target rules for targets named chatroom_server

# Build rule for target.
chatroom_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_server
.PHONY : chatroom_server

# fast build rule for target.
chatroom_server/fast:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/build
.PHONY : chatroom_server/fast

#=============================================================================
# Target rules for targets named chatroom

# Build rule for target.
chatroom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom
.PHONY : chatroom

# fast build rule for target.
chatroom/fast:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/build
.PHONY : chatroom/fast

#=============================================================================
# Target rules for targets named chatroom_client_form

# Build rule for target.
chatroom_client_form: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_client_form
.PHONY : chatroom_client_form

# fast build rule for target.
chatroom_client_form/fast:
	$(MAKE) -f CMakeFiles/chatroom_client_form.dir/build.make CMakeFiles/chatroom_client_form.dir/build
.PHONY : chatroom_client_form/fast

#=============================================================================
# Target rules for targets named chatroom_server_form

# Build rule for target.
chatroom_server_form: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_server_form
.PHONY : chatroom_server_form

# fast build rule for target.
chatroom_server_form/fast:
	$(MAKE) -f CMakeFiles/chatroom_server_form.dir/build.make CMakeFiles/chatroom_server_form.dir/build
.PHONY : chatroom_server_form/fast

#=============================================================================
# Target rules for targets named chatroom_client

# Build rule for target.
chatroom_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_client
.PHONY : chatroom_client

# fast build rule for target.
chatroom_client/fast:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/build
.PHONY : chatroom_client/fast

#=============================================================================
# Target rules for targets named clientui_autogen

# Build rule for target.
clientui_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientui_autogen
.PHONY : clientui_autogen

# fast build rule for target.
clientui_autogen/fast:
	$(MAKE) -f CMakeFiles/clientui_autogen.dir/build.make CMakeFiles/clientui_autogen.dir/build
.PHONY : clientui_autogen/fast

#=============================================================================
# Target rules for targets named serverui_autogen

# Build rule for target.
serverui_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serverui_autogen
.PHONY : serverui_autogen

# fast build rule for target.
serverui_autogen/fast:
	$(MAKE) -f CMakeFiles/serverui_autogen.dir/build.make CMakeFiles/serverui_autogen.dir/build
.PHONY : serverui_autogen/fast

#=============================================================================
# Target rules for targets named chatroom_server_autogen

# Build rule for target.
chatroom_server_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_server_autogen
.PHONY : chatroom_server_autogen

# fast build rule for target.
chatroom_server_autogen/fast:
	$(MAKE) -f CMakeFiles/chatroom_server_autogen.dir/build.make CMakeFiles/chatroom_server_autogen.dir/build
.PHONY : chatroom_server_autogen/fast

#=============================================================================
# Target rules for targets named chatroom_autogen

# Build rule for target.
chatroom_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_autogen
.PHONY : chatroom_autogen

# fast build rule for target.
chatroom_autogen/fast:
	$(MAKE) -f CMakeFiles/chatroom_autogen.dir/build.make CMakeFiles/chatroom_autogen.dir/build
.PHONY : chatroom_autogen/fast

#=============================================================================
# Target rules for targets named chatroom_client_form_autogen

# Build rule for target.
chatroom_client_form_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_client_form_autogen
.PHONY : chatroom_client_form_autogen

# fast build rule for target.
chatroom_client_form_autogen/fast:
	$(MAKE) -f CMakeFiles/chatroom_client_form_autogen.dir/build.make CMakeFiles/chatroom_client_form_autogen.dir/build
.PHONY : chatroom_client_form_autogen/fast

#=============================================================================
# Target rules for targets named chatroom_server_form_autogen

# Build rule for target.
chatroom_server_form_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_server_form_autogen
.PHONY : chatroom_server_form_autogen

# fast build rule for target.
chatroom_server_form_autogen/fast:
	$(MAKE) -f CMakeFiles/chatroom_server_form_autogen.dir/build.make CMakeFiles/chatroom_server_form_autogen.dir/build
.PHONY : chatroom_server_form_autogen/fast

#=============================================================================
# Target rules for targets named chatroom_client_autogen

# Build rule for target.
chatroom_client_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chatroom_client_autogen
.PHONY : chatroom_client_autogen

# fast build rule for target.
chatroom_client_autogen/fast:
	$(MAKE) -f CMakeFiles/chatroom_client_autogen.dir/build.make CMakeFiles/chatroom_client_autogen.dir/build
.PHONY : chatroom_client_autogen/fast

chatroom_autogen/3YJK5W5UP7/qrc_images.o: chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.o

.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.o

# target to build an object file
chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.o
.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.o

chatroom_autogen/3YJK5W5UP7/qrc_images.i: chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.i

.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.i

# target to preprocess a source file
chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.i
.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.i

chatroom_autogen/3YJK5W5UP7/qrc_images.s: chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.s

.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.s

# target to generate assembly for a file
chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.s
.PHONY : chatroom_autogen/3YJK5W5UP7/qrc_images.cpp.s

chatroom_autogen/mocs_compilation.o: chatroom_autogen/mocs_compilation.cpp.o

.PHONY : chatroom_autogen/mocs_compilation.o

# target to build an object file
chatroom_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/mocs_compilation.cpp.o
.PHONY : chatroom_autogen/mocs_compilation.cpp.o

chatroom_autogen/mocs_compilation.i: chatroom_autogen/mocs_compilation.cpp.i

.PHONY : chatroom_autogen/mocs_compilation.i

# target to preprocess a source file
chatroom_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/mocs_compilation.cpp.i
.PHONY : chatroom_autogen/mocs_compilation.cpp.i

chatroom_autogen/mocs_compilation.s: chatroom_autogen/mocs_compilation.cpp.s

.PHONY : chatroom_autogen/mocs_compilation.s

# target to generate assembly for a file
chatroom_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/chatroom_autogen/mocs_compilation.cpp.s
.PHONY : chatroom_autogen/mocs_compilation.cpp.s

chatroom_client_autogen/mocs_compilation.o: chatroom_client_autogen/mocs_compilation.cpp.o

.PHONY : chatroom_client_autogen/mocs_compilation.o

# target to build an object file
chatroom_client_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/chatroom_client_autogen/mocs_compilation.cpp.o
.PHONY : chatroom_client_autogen/mocs_compilation.cpp.o

chatroom_client_autogen/mocs_compilation.i: chatroom_client_autogen/mocs_compilation.cpp.i

.PHONY : chatroom_client_autogen/mocs_compilation.i

# target to preprocess a source file
chatroom_client_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/chatroom_client_autogen/mocs_compilation.cpp.i
.PHONY : chatroom_client_autogen/mocs_compilation.cpp.i

chatroom_client_autogen/mocs_compilation.s: chatroom_client_autogen/mocs_compilation.cpp.s

.PHONY : chatroom_client_autogen/mocs_compilation.s

# target to generate assembly for a file
chatroom_client_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/chatroom_client_autogen/mocs_compilation.cpp.s
.PHONY : chatroom_client_autogen/mocs_compilation.cpp.s

chatroom_client_form_autogen/mocs_compilation.o: chatroom_client_form_autogen/mocs_compilation.cpp.o

.PHONY : chatroom_client_form_autogen/mocs_compilation.o

# target to build an object file
chatroom_client_form_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client_form.dir/build.make CMakeFiles/chatroom_client_form.dir/chatroom_client_form_autogen/mocs_compilation.cpp.o
.PHONY : chatroom_client_form_autogen/mocs_compilation.cpp.o

chatroom_client_form_autogen/mocs_compilation.i: chatroom_client_form_autogen/mocs_compilation.cpp.i

.PHONY : chatroom_client_form_autogen/mocs_compilation.i

# target to preprocess a source file
chatroom_client_form_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client_form.dir/build.make CMakeFiles/chatroom_client_form.dir/chatroom_client_form_autogen/mocs_compilation.cpp.i
.PHONY : chatroom_client_form_autogen/mocs_compilation.cpp.i

chatroom_client_form_autogen/mocs_compilation.s: chatroom_client_form_autogen/mocs_compilation.cpp.s

.PHONY : chatroom_client_form_autogen/mocs_compilation.s

# target to generate assembly for a file
chatroom_client_form_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client_form.dir/build.make CMakeFiles/chatroom_client_form.dir/chatroom_client_form_autogen/mocs_compilation.cpp.s
.PHONY : chatroom_client_form_autogen/mocs_compilation.cpp.s

chatroom_server_autogen/mocs_compilation.o: chatroom_server_autogen/mocs_compilation.cpp.o

.PHONY : chatroom_server_autogen/mocs_compilation.o

# target to build an object file
chatroom_server_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/chatroom_server_autogen/mocs_compilation.cpp.o
.PHONY : chatroom_server_autogen/mocs_compilation.cpp.o

chatroom_server_autogen/mocs_compilation.i: chatroom_server_autogen/mocs_compilation.cpp.i

.PHONY : chatroom_server_autogen/mocs_compilation.i

# target to preprocess a source file
chatroom_server_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/chatroom_server_autogen/mocs_compilation.cpp.i
.PHONY : chatroom_server_autogen/mocs_compilation.cpp.i

chatroom_server_autogen/mocs_compilation.s: chatroom_server_autogen/mocs_compilation.cpp.s

.PHONY : chatroom_server_autogen/mocs_compilation.s

# target to generate assembly for a file
chatroom_server_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/chatroom_server_autogen/mocs_compilation.cpp.s
.PHONY : chatroom_server_autogen/mocs_compilation.cpp.s

chatroom_server_form_autogen/mocs_compilation.o: chatroom_server_form_autogen/mocs_compilation.cpp.o

.PHONY : chatroom_server_form_autogen/mocs_compilation.o

# target to build an object file
chatroom_server_form_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server_form.dir/build.make CMakeFiles/chatroom_server_form.dir/chatroom_server_form_autogen/mocs_compilation.cpp.o
.PHONY : chatroom_server_form_autogen/mocs_compilation.cpp.o

chatroom_server_form_autogen/mocs_compilation.i: chatroom_server_form_autogen/mocs_compilation.cpp.i

.PHONY : chatroom_server_form_autogen/mocs_compilation.i

# target to preprocess a source file
chatroom_server_form_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server_form.dir/build.make CMakeFiles/chatroom_server_form.dir/chatroom_server_form_autogen/mocs_compilation.cpp.i
.PHONY : chatroom_server_form_autogen/mocs_compilation.cpp.i

chatroom_server_form_autogen/mocs_compilation.s: chatroom_server_form_autogen/mocs_compilation.cpp.s

.PHONY : chatroom_server_form_autogen/mocs_compilation.s

# target to generate assembly for a file
chatroom_server_form_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server_form.dir/build.make CMakeFiles/chatroom_server_form.dir/chatroom_server_form_autogen/mocs_compilation.cpp.s
.PHONY : chatroom_server_form_autogen/mocs_compilation.cpp.s

clientui_autogen/mocs_compilation.o: clientui_autogen/mocs_compilation.cpp.o

.PHONY : clientui_autogen/mocs_compilation.o

# target to build an object file
clientui_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/clientui_autogen/mocs_compilation.cpp.o
.PHONY : clientui_autogen/mocs_compilation.cpp.o

clientui_autogen/mocs_compilation.i: clientui_autogen/mocs_compilation.cpp.i

.PHONY : clientui_autogen/mocs_compilation.i

# target to preprocess a source file
clientui_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/clientui_autogen/mocs_compilation.cpp.i
.PHONY : clientui_autogen/mocs_compilation.cpp.i

clientui_autogen/mocs_compilation.s: clientui_autogen/mocs_compilation.cpp.s

.PHONY : clientui_autogen/mocs_compilation.s

# target to generate assembly for a file
clientui_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/clientui_autogen/mocs_compilation.cpp.s
.PHONY : clientui_autogen/mocs_compilation.cpp.s

serverui_autogen/mocs_compilation.o: serverui_autogen/mocs_compilation.cpp.o

.PHONY : serverui_autogen/mocs_compilation.o

# target to build an object file
serverui_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/serverui_autogen/mocs_compilation.cpp.o
.PHONY : serverui_autogen/mocs_compilation.cpp.o

serverui_autogen/mocs_compilation.i: serverui_autogen/mocs_compilation.cpp.i

.PHONY : serverui_autogen/mocs_compilation.i

# target to preprocess a source file
serverui_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/serverui_autogen/mocs_compilation.cpp.i
.PHONY : serverui_autogen/mocs_compilation.cpp.i

serverui_autogen/mocs_compilation.s: serverui_autogen/mocs_compilation.cpp.s

.PHONY : serverui_autogen/mocs_compilation.s

# target to generate assembly for a file
serverui_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/serverui_autogen/mocs_compilation.cpp.s
.PHONY : serverui_autogen/mocs_compilation.cpp.s

src/client/login_dialog.o: src/client/login_dialog.cpp.o

.PHONY : src/client/login_dialog.o

# target to build an object file
src/client/login_dialog.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/login_dialog.cpp.o
.PHONY : src/client/login_dialog.cpp.o

src/client/login_dialog.i: src/client/login_dialog.cpp.i

.PHONY : src/client/login_dialog.i

# target to preprocess a source file
src/client/login_dialog.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/login_dialog.cpp.i
.PHONY : src/client/login_dialog.cpp.i

src/client/login_dialog.s: src/client/login_dialog.cpp.s

.PHONY : src/client/login_dialog.s

# target to generate assembly for a file
src/client/login_dialog.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/login_dialog.cpp.s
.PHONY : src/client/login_dialog.cpp.s

src/client/mainwindow_client.o: src/client/mainwindow_client.cpp.o

.PHONY : src/client/mainwindow_client.o

# target to build an object file
src/client/mainwindow_client.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/mainwindow_client.cpp.o
.PHONY : src/client/mainwindow_client.cpp.o

src/client/mainwindow_client.i: src/client/mainwindow_client.cpp.i

.PHONY : src/client/mainwindow_client.i

# target to preprocess a source file
src/client/mainwindow_client.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/mainwindow_client.cpp.i
.PHONY : src/client/mainwindow_client.cpp.i

src/client/mainwindow_client.s: src/client/mainwindow_client.cpp.s

.PHONY : src/client/mainwindow_client.s

# target to generate assembly for a file
src/client/mainwindow_client.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/mainwindow_client.cpp.s
.PHONY : src/client/mainwindow_client.cpp.s

src/client/qtabbar_h.o: src/client/qtabbar_h.cpp.o

.PHONY : src/client/qtabbar_h.o

# target to build an object file
src/client/qtabbar_h.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/qtabbar_h.cpp.o
.PHONY : src/client/qtabbar_h.cpp.o

src/client/qtabbar_h.i: src/client/qtabbar_h.cpp.i

.PHONY : src/client/qtabbar_h.i

# target to preprocess a source file
src/client/qtabbar_h.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/qtabbar_h.cpp.i
.PHONY : src/client/qtabbar_h.cpp.i

src/client/qtabbar_h.s: src/client/qtabbar_h.cpp.s

.PHONY : src/client/qtabbar_h.s

# target to generate assembly for a file
src/client/qtabbar_h.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/qtabbar_h.cpp.s
.PHONY : src/client/qtabbar_h.cpp.s

src/client/register_dialog.o: src/client/register_dialog.cpp.o

.PHONY : src/client/register_dialog.o

# target to build an object file
src/client/register_dialog.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/register_dialog.cpp.o
.PHONY : src/client/register_dialog.cpp.o

src/client/register_dialog.i: src/client/register_dialog.cpp.i

.PHONY : src/client/register_dialog.i

# target to preprocess a source file
src/client/register_dialog.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/register_dialog.cpp.i
.PHONY : src/client/register_dialog.cpp.i

src/client/register_dialog.s: src/client/register_dialog.cpp.s

.PHONY : src/client/register_dialog.s

# target to generate assembly for a file
src/client/register_dialog.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/register_dialog.cpp.s
.PHONY : src/client/register_dialog.cpp.s

src/client/tabpage.o: src/client/tabpage.cpp.o

.PHONY : src/client/tabpage.o

# target to build an object file
src/client/tabpage.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/tabpage.cpp.o
.PHONY : src/client/tabpage.cpp.o

src/client/tabpage.i: src/client/tabpage.cpp.i

.PHONY : src/client/tabpage.i

# target to preprocess a source file
src/client/tabpage.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/tabpage.cpp.i
.PHONY : src/client/tabpage.cpp.i

src/client/tabpage.s: src/client/tabpage.cpp.s

.PHONY : src/client/tabpage.s

# target to generate assembly for a file
src/client/tabpage.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/tabpage.cpp.s
.PHONY : src/client/tabpage.cpp.s

src/client/thread_client.o: src/client/thread_client.cpp.o

.PHONY : src/client/thread_client.o

# target to build an object file
src/client/thread_client.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/thread_client.cpp.o
.PHONY : src/client/thread_client.cpp.o

src/client/thread_client.i: src/client/thread_client.cpp.i

.PHONY : src/client/thread_client.i

# target to preprocess a source file
src/client/thread_client.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/thread_client.cpp.i
.PHONY : src/client/thread_client.cpp.i

src/client/thread_client.s: src/client/thread_client.cpp.s

.PHONY : src/client/thread_client.s

# target to generate assembly for a file
src/client/thread_client.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_client.dir/build.make CMakeFiles/chatroom_client.dir/src/client/thread_client.cpp.s
.PHONY : src/client/thread_client.cpp.s

src/main_client.o: src/main_client.cpp.o

.PHONY : src/main_client.o

# target to build an object file
src/main_client.cpp.o:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/src/main_client.cpp.o
.PHONY : src/main_client.cpp.o

src/main_client.i: src/main_client.cpp.i

.PHONY : src/main_client.i

# target to preprocess a source file
src/main_client.cpp.i:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/src/main_client.cpp.i
.PHONY : src/main_client.cpp.i

src/main_client.s: src/main_client.cpp.s

.PHONY : src/main_client.s

# target to generate assembly for a file
src/main_client.cpp.s:
	$(MAKE) -f CMakeFiles/clientui.dir/build.make CMakeFiles/clientui.dir/src/main_client.cpp.s
.PHONY : src/main_client.cpp.s

src/main_server.o: src/main_server.cpp.o

.PHONY : src/main_server.o

# target to build an object file
src/main_server.cpp.o:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/src/main_server.cpp.o
.PHONY : src/main_server.cpp.o

src/main_server.i: src/main_server.cpp.i

.PHONY : src/main_server.i

# target to preprocess a source file
src/main_server.cpp.i:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/src/main_server.cpp.i
.PHONY : src/main_server.cpp.i

src/main_server.s: src/main_server.cpp.s

.PHONY : src/main_server.s

# target to generate assembly for a file
src/main_server.cpp.s:
	$(MAKE) -f CMakeFiles/serverui.dir/build.make CMakeFiles/serverui.dir/src/main_server.cpp.s
.PHONY : src/main_server.cpp.s

src/server/mainwindow_server.o: src/server/mainwindow_server.cpp.o

.PHONY : src/server/mainwindow_server.o

# target to build an object file
src/server/mainwindow_server.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mainwindow_server.cpp.o
.PHONY : src/server/mainwindow_server.cpp.o

src/server/mainwindow_server.i: src/server/mainwindow_server.cpp.i

.PHONY : src/server/mainwindow_server.i

# target to preprocess a source file
src/server/mainwindow_server.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mainwindow_server.cpp.i
.PHONY : src/server/mainwindow_server.cpp.i

src/server/mainwindow_server.s: src/server/mainwindow_server.cpp.s

.PHONY : src/server/mainwindow_server.s

# target to generate assembly for a file
src/server/mainwindow_server.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mainwindow_server.cpp.s
.PHONY : src/server/mainwindow_server.cpp.s

src/server/mysql_utils.o: src/server/mysql_utils.cpp.o

.PHONY : src/server/mysql_utils.o

# target to build an object file
src/server/mysql_utils.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mysql_utils.cpp.o
.PHONY : src/server/mysql_utils.cpp.o

src/server/mysql_utils.i: src/server/mysql_utils.cpp.i

.PHONY : src/server/mysql_utils.i

# target to preprocess a source file
src/server/mysql_utils.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mysql_utils.cpp.i
.PHONY : src/server/mysql_utils.cpp.i

src/server/mysql_utils.s: src/server/mysql_utils.cpp.s

.PHONY : src/server/mysql_utils.s

# target to generate assembly for a file
src/server/mysql_utils.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/mysql_utils.cpp.s
.PHONY : src/server/mysql_utils.cpp.s

src/server/redis_utils.o: src/server/redis_utils.cpp.o

.PHONY : src/server/redis_utils.o

# target to build an object file
src/server/redis_utils.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/redis_utils.cpp.o
.PHONY : src/server/redis_utils.cpp.o

src/server/redis_utils.i: src/server/redis_utils.cpp.i

.PHONY : src/server/redis_utils.i

# target to preprocess a source file
src/server/redis_utils.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/redis_utils.cpp.i
.PHONY : src/server/redis_utils.cpp.i

src/server/redis_utils.s: src/server/redis_utils.cpp.s

.PHONY : src/server/redis_utils.s

# target to generate assembly for a file
src/server/redis_utils.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/redis_utils.cpp.s
.PHONY : src/server/redis_utils.cpp.s

src/server/thread_server.o: src/server/thread_server.cpp.o

.PHONY : src/server/thread_server.o

# target to build an object file
src/server/thread_server.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/thread_server.cpp.o
.PHONY : src/server/thread_server.cpp.o

src/server/thread_server.i: src/server/thread_server.cpp.i

.PHONY : src/server/thread_server.i

# target to preprocess a source file
src/server/thread_server.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/thread_server.cpp.i
.PHONY : src/server/thread_server.cpp.i

src/server/thread_server.s: src/server/thread_server.cpp.s

.PHONY : src/server/thread_server.s

# target to generate assembly for a file
src/server/thread_server.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom_server.dir/build.make CMakeFiles/chatroom_server.dir/src/server/thread_server.cpp.s
.PHONY : src/server/thread_server.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/chatroom.dir/build.make CMakeFiles/chatroom.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clientui"
	@echo "... serverui"
	@echo "... chatroom_server"
	@echo "... chatroom"
	@echo "... chatroom_client_form"
	@echo "... chatroom_server_form"
	@echo "... chatroom_client"
	@echo "... clientui_autogen"
	@echo "... serverui_autogen"
	@echo "... chatroom_server_autogen"
	@echo "... chatroom_autogen"
	@echo "... chatroom_client_form_autogen"
	@echo "... chatroom_server_form_autogen"
	@echo "... chatroom_client_autogen"
	@echo "... chatroom_autogen/3YJK5W5UP7/qrc_images.o"
	@echo "... chatroom_autogen/3YJK5W5UP7/qrc_images.i"
	@echo "... chatroom_autogen/3YJK5W5UP7/qrc_images.s"
	@echo "... chatroom_autogen/mocs_compilation.o"
	@echo "... chatroom_autogen/mocs_compilation.i"
	@echo "... chatroom_autogen/mocs_compilation.s"
	@echo "... chatroom_client_autogen/mocs_compilation.o"
	@echo "... chatroom_client_autogen/mocs_compilation.i"
	@echo "... chatroom_client_autogen/mocs_compilation.s"
	@echo "... chatroom_client_form_autogen/mocs_compilation.o"
	@echo "... chatroom_client_form_autogen/mocs_compilation.i"
	@echo "... chatroom_client_form_autogen/mocs_compilation.s"
	@echo "... chatroom_server_autogen/mocs_compilation.o"
	@echo "... chatroom_server_autogen/mocs_compilation.i"
	@echo "... chatroom_server_autogen/mocs_compilation.s"
	@echo "... chatroom_server_form_autogen/mocs_compilation.o"
	@echo "... chatroom_server_form_autogen/mocs_compilation.i"
	@echo "... chatroom_server_form_autogen/mocs_compilation.s"
	@echo "... clientui_autogen/mocs_compilation.o"
	@echo "... clientui_autogen/mocs_compilation.i"
	@echo "... clientui_autogen/mocs_compilation.s"
	@echo "... serverui_autogen/mocs_compilation.o"
	@echo "... serverui_autogen/mocs_compilation.i"
	@echo "... serverui_autogen/mocs_compilation.s"
	@echo "... src/client/login_dialog.o"
	@echo "... src/client/login_dialog.i"
	@echo "... src/client/login_dialog.s"
	@echo "... src/client/mainwindow_client.o"
	@echo "... src/client/mainwindow_client.i"
	@echo "... src/client/mainwindow_client.s"
	@echo "... src/client/qtabbar_h.o"
	@echo "... src/client/qtabbar_h.i"
	@echo "... src/client/qtabbar_h.s"
	@echo "... src/client/register_dialog.o"
	@echo "... src/client/register_dialog.i"
	@echo "... src/client/register_dialog.s"
	@echo "... src/client/tabpage.o"
	@echo "... src/client/tabpage.i"
	@echo "... src/client/tabpage.s"
	@echo "... src/client/thread_client.o"
	@echo "... src/client/thread_client.i"
	@echo "... src/client/thread_client.s"
	@echo "... src/main_client.o"
	@echo "... src/main_client.i"
	@echo "... src/main_client.s"
	@echo "... src/main_server.o"
	@echo "... src/main_server.i"
	@echo "... src/main_server.s"
	@echo "... src/server/mainwindow_server.o"
	@echo "... src/server/mainwindow_server.i"
	@echo "... src/server/mainwindow_server.s"
	@echo "... src/server/mysql_utils.o"
	@echo "... src/server/mysql_utils.i"
	@echo "... src/server/mysql_utils.s"
	@echo "... src/server/redis_utils.o"
	@echo "... src/server/redis_utils.i"
	@echo "... src/server/redis_utils.s"
	@echo "... src/server/thread_server.o"
	@echo "... src/server/thread_server.i"
	@echo "... src/server/thread_server.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

