// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_mainwindow_client.cpp"
#include "UVLADIE3JM/moc_mainwindow_server.cpp"
#include "UVLADIE3JM/moc_tabpage.cpp"
#include "UVLADIE3JM/moc_thread_client.cpp"
#include "UVLADIE3JM/moc_thread_server.cpp"
